### ISSUE TITLE
The ESPVFATFS can use on ESP32?

### ISSUE THREAD

**Issue by Vincentzpf** [Adam5Wu/ESPVFATFS#4]
Hi Zhenyu Wu,
看你这字名应该是一个中国人，所以我用中文跟你说。方便沟通理解更准确。
1.这个模块可以升级给EPS32使用吗?
2.如果使用长中文名为文件名是不是跟FATFS一样设定就可以了吗？
  把ffconf.h文件，的_USE_LFN修改为1。
  修改宏定义_CODE_PAGE为936，并添加cc936.c文件。

谢谢!
Vincent Zhang

**Comment by Adam5Wu** [comment]
理论上是的，不过我记得ESP32自带支持？你可以试试。:D

**Comment by Vincentzpf** [comment]
@Adam5Wu 谢谢！你的回复。你是说ESP32自带支持 FATFS ?

**Comment by Vincentzpf** [comment]
@Adam5Wu 我已经查到了,ESP32后官方已经集成了FatFs了。谢谢！
